# Generated by Django 4.0.1 on 2022-01-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newproj', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='departments',
        ),
        migrations.AddField(
            model_name='student',
            name='departments',
            field=models.ManyToManyField(related_name='dept', to='newproj.Department'),
        ),
    ]
